// Where every piece of content in the game comes from.
//
// The game ships no third-party files: the music is synthesized at runtime
// from note data written for this project, the interface sounds are
// oscillators, the icon is hand-drawn SVG and the text is set in whatever the
// player's system already has. The manifest states that per asset so the
// credits screen and ATTRIBUTION_AND_LICENSES.md can be generated from one
// list rather than kept in step by hand.

import type { TrackDefinition } from "../charts/ChartTypes";

export interface ManifestEntry {
  /** What the row is about, e.g. a track title with its id, or a file path. */
  asset: string;
  composer: string;
  /** Standing of the underlying composition, never of a performance. */
  compositionStatus: string;
  /** Where the note data being played came from. */
  arrangementSource: string;
  /** How sound is produced for it. */
  audioSource: string;
  licenseRationale: string;
  attributionRequired: boolean;
  /** Caveats worth printing, such as a work long credited to the wrong composer. */
  attributionNote?: string;
  /** The edition or reference the arrangement was written from. */
  sourceNote: string;
}

export const COMPOSITION_STATUS = "Public-domain composition";

export const ARRANGEMENT_SOURCE =
  "Original game arrangement based on a public-domain composition (project note-event data, no external MIDI)";

export const AUDIO_SOURCE = "Web Audio synthesis at runtime";

const NOT_APPLICABLE = "Not applicable";

/** Rows that are not tracks. They come last in the table. */
const NON_TRACK_ENTRIES: readonly ManifestEntry[] = [
  {
    asset: "Logo and icon",
    composer: NOT_APPLICABLE,
    compositionStatus: "Original artwork drawn for this game",
    arrangementSource:
      "Hand-written SVG in this repository. The lettering is constructed geometry on a 100 unit cap grid, not an outlined typeface, so no font file is involved.",
    audioSource: NOT_APPLICABLE,
    licenseRationale: "Part of this project's own source. No third-party rights are involved.",
    attributionRequired: false,
    sourceNote: "logo.svg, logo-plain.svg, public/mark.svg, public/favicon.svg",
  },
  {
    asset: "Interface and gameplay sounds",
    composer: NOT_APPLICABLE,
    compositionStatus: "Original, written for this game",
    arrangementSource: "Oscillator and noise voices defined in src/audio/SoundEffects.ts",
    audioSource: AUDIO_SOURCE,
    licenseRationale: "Generated by this project's own code. No sample libraries are used.",
    attributionRequired: false,
    sourceNote: "src/audio/SoundEffects.ts",
  },
  {
    asset: "Interface typeface",
    composer: NOT_APPLICABLE,
    compositionStatus: NOT_APPLICABLE,
    arrangementSource: "System font stack (system-ui with platform fallbacks)",
    audioSource: NOT_APPLICABLE,
    licenseRationale: "The page asks for fonts the player's device already has. No font file is bundled or fetched.",
    attributionRequired: false,
    sourceNote: "src/ui/styles.css, --font-stack",
  },
];

function trackEntry(def: TrackDefinition): ManifestEntry {
  const m = def.metadata;
  const entry: ManifestEntry = {
    asset: `${m.title} (${m.id})`,
    composer: m.catalogNumber ? `${m.composer}, ${m.catalogNumber}` : m.composer,
    compositionStatus: COMPOSITION_STATUS,
    arrangementSource: ARRANGEMENT_SOURCE,
    audioSource: AUDIO_SOURCE,
    licenseRationale: m.licenseNotes,
    // Public-domain compositions carry no legal attribution duty; the credits
    // name the composer anyway because it is the honest thing to print.
    attributionRequired: false,
    sourceNote: m.scoreSourceCredit,
  };
  if (m.attributionNote !== undefined) entry.attributionNote = m.attributionNote;
  return entry;
}

export function buildManifest(defs: readonly TrackDefinition[]): ManifestEntry[] {
  const tracks = [...defs].sort((a, b) => a.metadata.order - b.metadata.order).map(trackEntry);
  return [...tracks, ...NON_TRACK_ENTRIES];
}

/** Column headings, in the order the credits table and the markdown file use. */
export const MANIFEST_COLUMNS: readonly { key: keyof ManifestEntry; label: string }[] = [
  { key: "asset", label: "Asset" },
  { key: "composer", label: "Composer" },
  { key: "compositionStatus", label: "Composition" },
  { key: "arrangementSource", label: "Arrangement" },
  { key: "audioSource", label: "Audio" },
  { key: "licenseRationale", label: "Why it may be used" },
  { key: "sourceNote", label: "Source" },
];
